# Generated by Django 3.0.7 on 2020-06-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, storage='/media/images/', upload_to=''),
        ),
    ]
