# Generated by Django 3.0.7 on 2020-06-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
