# Generated by Django 3.0.7 on 2020-06-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200613_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='count',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fixed_price',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
